# ==========================================
# GMS - Script de Setup Automatique
# ==========================================
# Ce script crée toute la structure du projet

param(
    [string]$ProjectPath = "."
)

Set-Location $ProjectPath

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  GMS - Setup Automatique du Projet    " -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ==========================================
# ÉTAPE 1: Créer la structure des dossiers
# ==========================================

Write-Host "📁 Création de la structure des dossiers..." -ForegroundColor Yellow

$folders = @(
    ".github/workflows",
    ".github/ISSUE_TEMPLATE",
    "docs/screenshots",
    "scripts",
    "src/GMS.Domain",
    "src/GMS.Application",
    "src/GMS.Infrastructure",
    "src/GMS.Desktop",
    "src/GMS.Shared",
    "src/GMS.Tests",
    "logs",
    "backups"
)

foreach ($folder in $folders) {
    if (-not (Test-Path $folder)) {
        New-Item -ItemType Directory -Path $folder -Force | Out-Null
        Write-Host "  ✅ $folder" -ForegroundColor Green
    } else {
        Write-Host "  ⏭️  $folder (existe déjà)" -ForegroundColor Gray
    }
}

Write-Host ""

# ==========================================
# ÉTAPE 2: Créer .gitignore
# ==========================================

Write-Host "📝 Création du .gitignore..." -ForegroundColor Yellow

$gitignoreContent = @"
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio cache/options directory
.vs/

# Visual Studio Code
.vscode/

# JetBrains Rider
.idea/

# NuGet Packages
*.nupkg
*.snupkg
**/packages/*
!**/packages/build/
*.nuget.props
*.nuget.targets

# SQL Server files
*.mdf
*.ldf
*.ndf

# Database backups
*.bak
*.bakup

# Test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*
*.trx
*.coverage
*.coveragexml

# User secrets
appsettings.Development.json
appsettings.Production.json
**/appsettings.*.json
!**/appsettings.json

# Docker override files
docker-compose.override.yml

# Environment variables
.env
.env.local
.env.*.local

# Logs
logs/
*.log
npm-debug.log*

# OS files
.DS_Store
Thumbs.db

# Photos/uploads
**/wwwroot/uploads/
**/Photos/
**/Uploads/

# Backup files
backups/
*.bak
"@

Set-Content -Path ".gitignore" -Value $gitignoreContent -Encoding UTF8
Write-Host "  ✅ .gitignore créé" -ForegroundColor Green
Write-Host ""

# ==========================================
# ÉTAPE 3: Créer LICENSE (MIT)
# ==========================================

Write-Host "📄 Création de la LICENSE..." -ForegroundColor Yellow

$year = (Get-Date).Year
$licenseContent = @"
MIT License

Copyright (c) $year Heinkek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"@

Set-Content -Path "LICENSE" -Value $licenseContent -Encoding UTF8
Write-Host "  ✅ LICENSE créée" -ForegroundColor Green
Write-Host ""

# ==========================================
# ÉTAPE 4: Créer les templates GitHub
# ==========================================

Write-Host "🐙 Création des templates GitHub..." -ForegroundColor Yellow

# Bug report template
$bugReportContent = @"
---
name: Bug report
about: Créer un rapport de bug
title: '[Bug] '
labels: bug
assignees: ''
---

## 🐛 Description du bug
Une description claire et concise du bug.

## 📋 Étapes pour reproduire
1. Aller sur '...'
2. Cliquer sur '...'
3. Descendre jusqu'à '...'
4. Voir l'erreur

## ✅ Comportement attendu
Ce qui devrait se passer.

## ❌ Comportement actuel
Ce qui se passe réellement.

## 📸 Screenshots
Si applicable, ajouter des captures d'écran.

## 💻 Environnement
- OS: [ex. Windows 10 Pro 22H2]
- Version GMS: [ex. 1.0.0]
- .NET Version: [ex. 8.0.1]

## 📝 Logs
\`\`\`
Copier les logs pertinents ici
\`\`\`

## ℹ️ Informations additionnelles
Tout autre contexte utile.
"@

Set-Content -Path ".github/ISSUE_TEMPLATE/bug_report.md" -Value $bugReportContent -Encoding UTF8

# Feature request template
$featureRequestContent = @"
---
name: Feature request
about: Suggérer une nouvelle fonctionnalité
title: '[Feature] '
labels: enhancement
assignees: ''
---

## 💡 Problème à résoudre
Une description claire du problème que cette fonctionnalité résoudrait.

## ✨ Solution proposée
Décrivez comment vous voyez cette fonctionnalité fonctionner.

## 🔄 Alternatives considérées
Décrivez les solutions alternatives que vous avez envisagées.

## 📊 Cas d'usage
Exemples concrets d'utilisation de cette fonctionnalité.

## ℹ️ Contexte additionnel
Tout autre contexte, screenshots ou liens utiles.
"@

Set-Content -Path ".github/ISSUE_TEMPLATE/feature_request.md" -Value $featureRequestContent -Encoding UTF8

# Pull request template
$prTemplateContent = @"
## 📝 Description
[Description claire de ce que fait cette PR]

## 🔗 Issue liée
Closes #[numéro de l'issue]

## 🔧 Type de changement
- [ ] 🐛 Bug fix (changement qui corrige un problème)
- [ ] ✨ Nouvelle fonctionnalité
- [ ] 💥 Breaking change (correction ou fonctionnalité qui change le comportement existant)
- [ ] 📝 Documentation
- [ ] ⚡ Performance
- [ ] ♻️ Refactorisation

## 🧪 Comment a été testé ?
[Décrivez les tests effectués]

## 📸 Screenshots (si applicable)
[Ajoutez des captures d'écran]

## ✅ Checklist
- [ ] Mon code suit les standards du projet
- [ ] J'ai effectué une auto-revue de mon code
- [ ] J'ai commenté les parties complexes
- [ ] J'ai mis à jour la documentation
- [ ] Mes changements ne génèrent pas de nouveaux warnings
- [ ] J'ai ajouté des tests qui prouvent que ma correction fonctionne
- [ ] Les tests unitaires existants passent localement
- [ ] CHANGELOG.md mis à jour
"@

Set-Content -Path ".github/PULL_REQUEST_TEMPLATE.md" -Value $prTemplateContent -Encoding UTF8

Write-Host "  ✅ Templates GitHub créés" -ForegroundColor Green
Write-Host ""

# ==========================================
# ÉTAPE 5: Créer la solution .NET
# ==========================================

Write-Host "🔨 Création de la solution .NET..." -ForegroundColor Yellow

if (-not (Test-Path "GMS.sln")) {
    dotnet new sln -n GMS
    Write-Host "  ✅ Solution GMS.sln créée" -ForegroundColor Green
} else {
    Write-Host "  ⏭️  GMS.sln existe déjà" -ForegroundColor Gray
}

Write-Host ""

# ==========================================
# ÉTAPE 6: Créer les projets
# ==========================================

Write-Host "📦 Création des projets .NET..." -ForegroundColor Yellow

$projects = @(
    @{Name="GMS.Domain"; Type="classlib"; Path="src/GMS.Domain"},
    @{Name="GMS.Application"; Type="classlib"; Path="src/GMS.Application"},
    @{Name="GMS.Infrastructure"; Type="classlib"; Path="src/GMS.Infrastructure"},
    @{Name="GMS.Shared"; Type="classlib"; Path="src/GMS.Shared"},
    @{Name="GMS.Desktop"; Type="wpf"; Path="src/GMS.Desktop"},
    @{Name="GMS.Tests"; Type="xunit"; Path="src/GMS.Tests"}
)

foreach ($project in $projects) {
    $projectFile = "$($project.Path)/$($project.Name).csproj"
    
    if (-not (Test-Path $projectFile)) {
        dotnet new $($project.Type) -n $($project.Name) -o $($project.Path)
        dotnet sln add $projectFile
        Write-Host "  ✅ $($project.Name) créé" -ForegroundColor Green
    } else {
        Write-Host "  ⏭️  $($project.Name) existe déjà" -ForegroundColor Gray
    }
}

Write-Host ""

# ==========================================
# ÉTAPE 7: Configurer les références entre projets
# ==========================================

Write-Host "🔗 Configuration des références entre projets..." -ForegroundColor Yellow

dotnet add src/GMS.Application/GMS.Application.csproj reference src/GMS.Domain/GMS.Domain.csproj
dotnet add src/GMS.Infrastructure/GMS.Infrastructure.csproj reference src/GMS.Domain/GMS.Domain.csproj
dotnet add src/GMS.Infrastructure/GMS.Infrastructure.csproj reference src/GMS.Application/GMS.Application.csproj
dotnet add src/GMS.Desktop/GMS.Desktop.csproj reference src/GMS.Application/GMS.Application.csproj
dotnet add src/GMS.Desktop/GMS.Desktop.csproj reference src/GMS.Infrastructure/GMS.Infrastructure.csproj
dotnet add src/GMS.Desktop/GMS.Desktop.csproj reference src/GMS.Shared/GMS.Shared.csproj

Write-Host "  ✅ Références configurées" -ForegroundColor Green
Write-Host ""

# ==========================================
# ÉTAPE 8: Copier docker-entrypoint.sh et chmod
# ==========================================

Write-Host "🐳 Configuration Docker..." -ForegroundColor Yellow

# Rendre docker-entrypoint.sh exécutable sur Linux/Mac
if (Test-Path "docker-entrypoint.sh") {
    Write-Host "  ✅ docker-entrypoint.sh trouvé" -ForegroundColor Green
} else {
    Write-Host "  ⚠️  docker-entrypoint.sh manquant - créez-le manuellement" -ForegroundColor Yellow
}

Write-Host ""

# ==========================================
# ÉTAPE 9: Premier build
# ==========================================

Write-Host "🔨 Premier build du projet..." -ForegroundColor Yellow

try {
    dotnet restore
    dotnet build --configuration Debug
    Write-Host "  ✅ Build réussi!" -ForegroundColor Green
} catch {
    Write-Host "  ⚠️  Build échoué - vérifiez les erreurs ci-dessus" -ForegroundColor Yellow
}

Write-Host ""

# ==========================================
# RÉSUMÉ
# ==========================================

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ✅ SETUP TERMINÉ!                     " -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "📁 Structure créée:" -ForegroundColor Yellow
Write-Host "  ✅ Dossiers du projet"
Write-Host "  ✅ .gitignore"
Write-Host "  ✅ LICENSE (MIT)"
Write-Host "  ✅ Templates GitHub"
Write-Host "  ✅ Solution .NET (GMS.sln)"
Write-Host "  ✅ 6 projets"
Write-Host "  ✅ Références configurées"
Write-Host ""
Write-Host "🚀 PROCHAINES ÉTAPES:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Copier les fichiers Markdown:" -ForegroundColor White
Write-Host "   - README.md" -ForegroundColor Cyan
Write-Host "   - CONTRIBUTING.md" -ForegroundColor Cyan
Write-Host "   - CHANGELOG.md" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. Copier les fichiers Docker:" -ForegroundColor White
Write-Host "   - docker-compose.yml" -ForegroundColor Cyan
Write-Host "   - Dockerfile" -ForegroundColor Cyan
Write-Host "   - docker-entrypoint.sh" -ForegroundColor Cyan
Write-Host "   - .dockerignore" -ForegroundColor Cyan
Write-Host "   - .env.example" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. Copier les scripts:" -ForegroundColor White
Write-Host "   - scripts/init-db.sql" -ForegroundColor Cyan
Write-Host "   - .github/workflows/ci.yml" -ForegroundColor Cyan
Write-Host ""
Write-Host "4. Initialiser Git:" -ForegroundColor White
Write-Host "   git init" -ForegroundColor Cyan
Write-Host "   git add ." -ForegroundColor Cyan
Write-Host "   git commit -m 'Initial commit'" -ForegroundColor Cyan
Write-Host "   git remote add origin https://github.com/Heinkek-99/GMS-School-Management.git" -ForegroundColor Cyan
Write-Host "   git push -u origin main" -ForegroundColor Cyan
Write-Host ""
Write-Host "5. Lancer Docker:" -ForegroundColor White
Write-Host "   docker-compose up -d" -ForegroundColor Cyan
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Bon développement! 🎉" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan